Step2 - String calculator
next-step/swift-racingcar pull request #16
Opened 2021-10-31 16:47 UTC by mephrine

Step2 - 문자열 계산기
---
안녕하세요 리뷰어님!<br>
브런치 실수로 인해서(step1에서 작업을 하고있단걸 늦게 깨닫고 rebase를...ㅠㅠ)<br>
2021. 10. 31일 merge 커밋 이후부터 봐주시면 감사하겠습니다!!

## Works
- 문자열 사칙 연산 계산기 구현
    - Calculator
    - ValueError
    - ArithmeticOperator

## Questions
- [ ] 현업에서 영어 커밋 메시지 사용 여부

지난 강의에서 들은 **커밋메시지 작성 법** 관련 블로그들을 보니 다 영어로 커밋을 하시길래,<br>
영어로만 해야되는 것으로 알고 부족한 영어 실력으로 도전을 해봤습니다...<br>
(제가 지금 봐도 엉망인 게 많아서... 부디 리뷰어님의 너그러운 마음으로 이해해주시길 바랍니다 ㅜ)<br>
실제 현업에서도 많이들 영어로 커밋을 작성하시는지 궁금합니다!

<br>

- [ ] 리뷰어 입장에서의 잦은 커밋의 효율

지난 강의에 야곰님께서 본인은 **날아가도 아깝지 않을 정도**로 커밋을 하신다고 말씀해주셔서,<br>
저는 기존에 한 기능 단위로 커밋을 해왔었지만, 이번에는 야곰님을 따라 나름 세부적으로 커밋을 해보았습니다.<br><br>
근데 이렇게 작업을 하고 PR을 생성해보니 너무 커밋이 많은 것 같아서,<br>
리뷰어 입장에서 리뷰하는데 더 꼼꼼히 하실 수 있어서 좋으신지,<br>
아니면 오히려 힘이 들고 더 리뷰하기 어려운지가 궁금합니다!!

<br>

- [ ] 올바른 테스트 코드 작성

테스트 코드를 작성했지만, 이렇게 작성하는 것이 맞는지 모르겠습니다...<br>
(e.g. 생각나는 에러 발생 케이스를 막 만들어서 테스트 돌려보기 - 제 테스트 코드에서 XCTAssertThrowsError를 사용하는 부분입니다.)

<br>

- [ ] TDD

제 나름대로 TDD로 구현을 해보았는데,<br>
요번에 진행한 방식으로 진행하는 것이 맞는지 궁금합니다!<br>
(실패하는 테스트 작성 -> 구현 -> 리팩토링)

2021-11-01 15:46 UTC, zdodev requested changes
@mephrine 안녕하세요~ 수고하습니다!

전체적으로 컨벤션을 맞추고 메서드의 역할을 분리하여 작성하신 점이 눈에 띄었습니다!
다양한 경우의 수에 대한 테스트도 잘 작성해 주셨습니다👍

커밋 메시지에 대한 사항은 팀 규칙에 따라 많이 다르지 않을까 싶습니다.
작성하는 사람과 메시지를 읽는 사람이 읽기 편한 언어로 작성하기 않을까 싶습니다.

커밋 메시지를 자주 남기더라도 일관성있게 남겨주신다면 잦은 커밋이 나쁠 이유가 없지 않을까 싶습니다.
코드를 작성하신 단위와 수행한 작업에 대한 내용을 커밋 메시지에 잘 남겨주셔서 이해하기 편했습니다~

다양한 경우의 수에 대한 테스트를 작성해주셔서 테스트를 잘 작성했다고 생각합니다. TDD 진행 방식은 말씀해주신 방법이 맞습니다.

몇 가지 궁금증을 남겨보았습니다~
이해가 잘 안되거나 어려운 점에 대해서 공유하거나 이야기 나눠주시면 좋겠습니다.😊

2021-11-01 15:46 UTC, zdodev commented on RacingCar/ArithmeticOperator.swift
> +enum ArithmeticOpearator: String {
enum으로 operator 타입을 구현하셨네요. 좋습니다!

2021-11-01 15:46 UTC, zdodev commented on RacingCar/ArithmeticOperator.swift
> +	}
연산 메서드 하나만 외부에 노출하고 내부 사칙연산 메서드를 `private`으로 구현하신 점이 인상 깊습니다!

2021-11-01 15:46 UTC, zdodev commented on RacingCar/Calculator.swift
> +		for i in findOperatorRange(in: expressions) {
for문의 `i` 대신 다른 이름을 사용해 보는 것은 어떨까요? 의미를 나타낼 수 있는 다른 이름을 지어볼 수 있을까요?🤔

2021-11-01 15:46 UTC, zdodev commented on RacingCar/Calculator.swift
> +			result = try arithmeticOperator.operate(result, operand)
`result` 변수의 역할은 무엇일까요?🤔 네이밍에 맞게 피연산자의 역할과 연산 결과의 역할을 나눠볼 수 있을까요?

2021-11-01 15:46 UTC, zdodev commented on RacingCar/Calculator.swift
> +	}
범위 지정 역할을 분리하셨네요. 좋습니다!

2021-11-01 15:46 UTC, zdodev commented on RacingCar/ValueError.swift
> +enum ValueError: Error {
ValueError 타입을 구현하셨네요. 좋습니다!

2021-11-01 15:46 UTC, zdodev commented on RacingCarTest/CalculatorTest.swift
> +	}
사칙연산에 대한 테스트 잘 작성해주셨습니다!

2021-11-01 15:46 UTC, zdodev commented on RacingCarTest/CalculatorTest.swift
> +	}
nil 및 빈값에 대한 테스트 잘 작성해주셨습니다! 예외 발생에 따른 XCTAssertThrowsError 구문을 잘 활용해주셨네요!

2021-11-01 15:46 UTC, zdodev commented on RacingCarTest/CalculatorTest.swift
> +	}
여러 가지 예외 상황 입력에 대한 테스트 잘 작성해주셨습니다!

2021-11-02 11:18 UTC, mephrine commented on RacingCar/Calculator.swift
> +		for i in findOperatorRange(in: expressions) {
좋은 지적 감사합니다!`i`변수명은  `operatorIndex` 로 이름을 변경해봤습니다.

2021-11-02 11:29 UTC, mephrine commented on RacingCar/Calculator.swift
> +			result = try arithmeticOperator.operate(result, operand)
@zdodev 리뷰어 님께서 말씀주신 내용이 처음에 이해하기가 어려웠지만... 😱
나름대로 곰곰히 생각을 해본 결과를 수정해봤습니다!

말씀주신 `result`변수의 역할은 계산 결과를 저장하는 용도가 맞는 것 같습니다.

현재 코드에서는 `result` 변수가 피연산자의 역할도 하고 있어서
`result`는 결과를 저장하는 용도로만 사용하도록 변경하고,

operands 튜플을 만들어서 LHS에 result를, RHS에 RHS 피연산자를 넣어서
사용해보는 방식으로 변경해봤습니다.

2021-11-02 11:36 UTC, mephrine commented
## Review Notes
- `i` 변수명 수정 : `operatorIndex`가 더 명확하다고 판단하여 해당 이름으로 변경했습니다.

- `result`의 다중 역할 분리 : 결과를 저장하는 용도로만 사용하고, LHS로 사용하던 부분은 operand tuple에 담아서 사용했습니다.

2021-11-03 05:02 UTC, zdodev approved these changes
네이밍과 역할 분리가 전보다 잘 이루어진 점이 보입니다!

이번 스텝은 여기서 마무리하고 다음 스텝 진행하시면 될 것 같습니다.

2021-11-03 05:02 UTC, zdodev commented on RacingCar/Calculator.swift
> +		for operatorIndex in findOperatorRange(in: expressions) {
전보다 명확한 역할과 네이밍이 되었네요!

2021-11-03 05:02 UTC, zdodev commented on RacingCar/Calculator.swift
> +			result = try arithmeticOperator.operate(operands.lhs, operands.rhs)
변수들의 역할 분리 좋습니다!

2021-11-03 05:02 UTC, merged