Step3 - 자동차 경주
next-step/swift-racingcar pull request #22
Opened 2021-11-05 15:28 UTC by NamKiBeom

### Step3 목표
- 구현은 나중에 하고 요구사항에 따라 도메인 로직에 대한 테스트 케이스 작성으로 먼저 시작한다.
- 순서는 테스트케이스 작성(Red) -> Stub Class로 테스트케이스가 통과되도록 구현(Green) -> 리펙토링(Blue)
- 처음부터 완벽한 설계를 할 필요는 없다. 처음부터 완벽해지기 위해 고민하는 시간을 줄이자.(짠 코드를 버리는 과정도 필요)
- 리펙터링 과정에서만 더 나은 설계에 대해 고민 할 것

### P.S.
야곰님의 말씀처럼 PR을 미리 올려서 개발 과정이 보여지는 것도 좋을 것 같아서 미리 올립니다. 
리뷰 요청은 개발이 완료되는 시점에 요청 드리겠습니다.

2021-11-08 13:19 UTC, wonhee009 requested changes
@NamKiBeom 스텝3 수고하셨습니다!🎉
로직들을 잘 구분하신거 같습니다.
리뷰와 궁금한 부분들 남겨놓았습니다.🙏

- 크리티컬한 부분은 아니지만 현재는 입출력이 한줄로 나오진 않는데요. 가능하다면 프로젝트 실행 결과랑 동일한 것도 괜찮지 않을까 생각합니다😀
<img width="178" alt="image" src="https://user-images.githubusercontent.com/30456206/140745503-ad34d56e-b595-4a5a-985e-2f86b5d44e9b.png">

- 커버리지도 확인해보셨을까요?🤔

2021-11-08 13:19 UTC, wonhee009 commented on RacingCar/RacingGameViewController.swift
> +import Combine
컴바인을 사용하셨군용😀

2021-11-08 13:19 UTC, wonhee009 commented on RacingCar/RacingGameViewModel.swift
> +}
`RacingGameInputProtocol`이라는 네이밍이 어색해 보이는데요.
`input`이라고 하니까 사용자가 입력하는 부분과 관련된 기능을 할거 같아서요.🤔

2021-11-08 13:19 UTC, wonhee009 commented on RacingCar/RacingGameViewModel.swift
> +    func startRacing(carCount: Int) {
carCount는 사용하지 않는 파라미터인거 같습니다.🥲

2021-11-08 13:19 UTC, wonhee009 commented on RacingCar/RacingGameViewModel.swift
> +    var carPositionSubject = PassthroughSubject<[Int], Never>()
이건 그냥 순수하게 궁금한건데요.
`[Int]`로 정의한 이유가 있을까요?
`[String]`으로 정의해도 괜찮지 않았을까 해서요! 그냥 이유가 궁금한거니 편하게 말씀해주세요😃

2021-11-08 13:19 UTC, wonhee009 commented on RacingCar/RacingGameViewModel.swift
> +    func tryForward(_ fuel: Int)
tryForward같은 경우는 에러가 있어야할거 같은데 다른 네이밍은 어떨까요..?🤔

2021-11-11 12:40 UTC, NamKiBeom commented on RacingCar/RacingGameViewController.swift
> +import Combine
ㅎㅎ써보고 싶어서 써봤습니다

2021-11-11 12:41 UTC, NamKiBeom commented on RacingCar/RacingGameViewModel.swift
> +}
앗.. 그러네요 수정하겠습니다.

2021-11-11 12:42 UTC, NamKiBeom commented on RacingCar/RacingGameViewModel.swift
> +    func startRacing(carCount: Int) {
어우... 리펙터링하면서 줄이다보니 깜빡헀네요

2021-11-11 13:12 UTC, NamKiBeom commented on RacingCar/RacingGameViewModel.swift
> +    var carPositionSubject = PassthroughSubject<[Int], Never>()
음... 이거는  의식의 흐름대로 뭔가 차의 포지션 자체는 정수로 가지고 있어야한다고 생각했고 도출될 때 로직을 수행해야된다고 생각했어요!
처음 들어온 데이터타입은 최대한 그대로 받고 고차함수를 써서 가공해서 외부로 도출하는 것 같아요.. 그러기 위해서 Int 그대로 놔두고 Publisher로 뺏습니다.
원래 생성되는 데이터 자체를 private하게 관리하고 싶었습니다. OutputProtocol로 Subject property를 정의해버리다보니 private을 못써서 아쉽더라구요. 이유는 Subject를 통해 외부에서 이벤트를 주입받지 않기 위함인데요.. 혹시 좋은 방법이 있다면 추천드립니다.

2021-11-11 13:21 UTC, NamKiBeom commented on RacingCar/RacingGameViewModel.swift
> +    func tryForward(_ fuel: Int)
뭔가 앞으로 가는걸 시도하는 느낌이라 try를 쓰긴했는데 attempt라는 단어도 있었네요! 수정하겠습니다.

2021-11-12 02:30 UTC, wonhee009 commented on RacingCar/RacingGameViewModel.swift
> +    var carPositionSubject = PassthroughSubject<[Int], Never>()
으으음..... 왜 이렇게 정의 되었는지 이해했습니다.
현재 `carPositionSubject가 OutputProtocol에 정의되어져 있는데 이 부분은 RacingGameMaterialProtocol <- 여기에 있는게 좀 더 맞지 않나?라는 생각이 들기도 하구요.
OutputProtocol은 말 그대로 출력을 위한 프로토콜로 이해했는데 carPosition은 출력만을 위한 요소는 아니지 않나?라는 생각이 들긴하네요.🤔

2021-11-12 12:53 UTC, NamKiBeom commented on RacingCar/RacingGameViewModel.swift
> +    var carPositionSubject = PassthroughSubject<[Int], Never>()
리뷰 반영했습니다~!

2021-11-12 12:59 UTC, wonhee009 approved these changes
수고하셨습니다😀

2021-11-12 13:00 UTC, merged