3단계 - 자동차 경주
next-step/swift-racingcar pull request #24
Opened 2021-11-08 11:22 UTC by hiddenparts

2단계의 피드백를 바탕으로 먼저 테스트케이스를 작성하면서 구현해보려고 노력했으나
생각보다 어떤부분에서 어떻게 시작해야할지 막막함을 느끼면서 과제를 진행한거 같습니다.

InputView, ResultView의 타입의 분리라는 정확하게 이해가 안되어서 제가 나름 이해한대로 작성해보았는데 
이부분에 대한 좋은 피드백 부탁드립니다!

2021-11-09 10:44 UTC, hiddenparts commented
그러고보니 기존 프로젝트에 계속 이어서 진행하면 되는건지 궁금하고,
뭔가 요구사항이 적어서 금방 해버려서 이렇게 하는게 맞나 싶네요🤔

2021-11-09 13:06 UTC, uuu1101 requested changes
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)문서와 제가 첨부드린 문서를 한번 읽어보시면 좋을것 같아요.
commit의 단위를 조금 더 나누어 보는것도 좋을 것 같아요. commit 메세지 작성에 관련된 문서도 [학습공간](https://edu.nextstep.camp/s/sdGlkvxo/ls/VROoF5uD)에 있으니 읽어보시는게 도움이 될 것 같습니다. 👍 
구조체 구현과 테스트 코드 작성이 하나의 커밋보다는 따로 나눠지는게 더 좋지 않을까 합니다 😊

2021-11-09 13:06 UTC, uuu1101 commented on RacingCar/RacingCar.swift
> +    static func getCarCount() -> Int {
메서드 명에 get을 사용하고 계시는데, [이 문서](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html)를 한번 읽어보셔도 좋을 것 같습니다 ☺️

2021-11-09 13:06 UTC, uuu1101 commented on RacingCar/RacingCar.swift
> +            return -1
-1을 리턴 하신 이유가 있으실까요?!

2021-11-09 13:06 UTC, uuu1101 commented on RacingCar/RacingCar.swift
> +struct ResultView {
위의 InputView 와 함께 딱 보았을때 뭔가 UI에 대한 것이라고 생각이 드는 네이밍처럼 느껴졌어요 ..! ㅎㅎ 
RacingCar 라는 폴더를 보고 UI와 관련있다라고 알 수 없어서 폴더를 분리하여 나타내시거나, 다른 네이밍이 좋아보입니다.

2021-11-09 13:06 UTC, uuu1101 commented on RacingCar/RacingCar.swift
> +        for i in 0..<cars.count {
i는 어떤 걸 나타내는 걸까요?! 🤔

2021-11-09 13:06 UTC, uuu1101 commented on RacingCar/RacingCar.swift
> +            cars[i].race()
foreach문을 사용하거나, for car in cars 를 사용하는건 어떻게 생각하시나요?

2021-11-15 14:45 UTC, hiddenparts commented on RacingCar/RacingCar.swift
> +            return -1
이번엔 try catch를 쓰지않으려고 잘못 입력되었을때를 나타내는 뜻으로 -1을 리턴하게 해보았습니다.

2021-11-15 14:46 UTC, hiddenparts commented on RacingCar/RacingCar.swift
> +            cars[i].race()
car가 struct다보니 foeach나 for in 문에서 복사가 일어나는 바람에 반영이 안되서 어쩔 수 없이 index를 사용했네요 ;

2021-11-15 15:30 UTC, hiddenparts commented
에고 이런저런 바쁜일들 때문에 이제서야 리뷰 요청을 보내네요 ㅠ
정신없이 피드백을 보다보니 테스트케이스에 대해서는 전혀 신경을 쓰지 못했네요.
코멘트 남겨주신 부분만 Swift API 디자인 가이드라인과 Naming Methods를 보면서 고민해보는 시간만 가졌습니다.
테스트 코드 쪽으로는 피드백이 없으실까요? 
현재 코드의 동작이 간단해서 더 이상의 테스트를 생각이 나지않는데 
어떤 방향으로 생각해보라던지, 이런 테스트는 어떨런지 등 TDD 지식이 거의 0에 가깝다보니 감이라도 잡을 수 있는 힌트가 있을까요? (이 코드에 한해서)

2021-11-17 16:00 UTC, merged

2021-11-17 16:05 UTC, uuu1101 commented
에고, 제가 모르고 로또하신걸 리뷰달았었는데, 착각을 해버렸네요..
`Swift API 디자인 가이드라인과 Naming Methods를 보면서 고민해보는 시간만 가졌습니다.` 충분히 많은걸 하신것 같네요 👏👏
테스트 코드 쪽으로 말씀드리자면,개인적으로는 이동을 몇번 할 것인지, 랜덤한 숫자들은 어떻게 테스트를 하면 좋을지에 대한 고민을 더 해보았을것 같습니다.
요구사항에서 연관되는 많은 경우의 수를 고민해보는게 좋을것 같아요. 로또에서 작성하신 부분을 보니 충분히 고민을 많이 하고 계신거 같네요 :) 
그 기능을 구현 하였을때 어떤 것들을 검증하면 좋을지..를 방향으로 잡아보시는건 어떨까요?! 
이번 스텝도 고생하셨습니다 👍