Step4 - 자동차 경주(우승자)
next-step/swift-racingcar pull request #28
Opened 2021-11-11 14:22 UTC by Mino777

바쁘신데 항상 좋은 리뷰 남겨주셔서 감사드립니다!!

- RacingGame()에 테스트 커버리지를 높여보려고 좀 억지로 파라미터도 늘려보고 직접 값을 주입해서 테스트 해보았는데 너무 안이뻐보여서 다시 수정하여 최대한 현재 상황에서 할 수 있는 부분만 남겼습니다!
- 접근제어자가 안지켜진 부분들은 테스트를 위함입니다!
- 바쁘다는 핑계로 예외처리가 좀 부족한 것 같습니다ㅠㅠ 추후에 계속 디벨롭시키겠습니다!

감사합니다!

2021-11-12 14:52 UTC, zdodev requested changes
@Mino777 안녕하세요!

스텝4 구현하시느라 고생하셨습니다!
전체적으로 프로그래밍 요구 사항에 맞게 잘 작성해주셨습니다!

테스트 커버리지를 더 많이 포함하도록 변경해보면 좋을 것 같습니다!

몇 가지 코멘트를 남겨보았습니다~
어려운 점 있으시면 이야기 나눠주시면 좋겠습니다.😊

2021-11-12 14:52 UTC, zdodev commented on RacingCar/Step34/Car.swift
> +    init(name: String ,position: String = GameOption.defaultPosition) {
파라미터에서 `String ,position` 공백 위치가 다른 메서드와 살짝 다릅니다!

2021-11-12 14:52 UTC, zdodev commented on RacingCar/Step34/RacingGame.swift
> +    }
`findWinner` 메서드에서 우승자도 찾고 결과도 출력하는 역할을 수행하고 있습니다. 우승자를 찾는 부분과 결과를 출력하는 부분을 나눠볼 수 있을까요? 나눠보면 테스트를 수행하기 더 쉬워지지 않을까 생각합니다!

2021-11-12 14:52 UTC, zdodev commented on RacingCar/Step34/RacingGame.swift
> +    }
`attemptToMoveCar` 메서드에서 경기 수만큼 게임을 진행하면서 진행 결과를 출력하는 역할을 수행하고 있습니다. 이 역할을 분리해 볼 수 있을까요? 출력 부분을 분리하면 테스트 수행하기 더 쉬워질 것 같습니다!

2021-11-13 06:58 UTC, Mino777 commented on RacingCar/Step34/Car.swift
> +    init(name: String ,position: String = GameOption.defaultPosition) {
앗!! 예리한 피드백 감사드립니당 수정했씁니다!

2021-11-13 12:54 UTC, Mino777 commented on RacingCar/Step34/RacingGame.swift
> +    }
맞습니다! 결과를 출력하는 부분을 메서드로 나눠보았습니다!

2021-11-13 13:10 UTC, Mino777 commented on RacingCar/Step34/RacingGame.swift
> +    }
맞습니다! 메서드로 분리해보았습니다!

2021-11-13 13:11 UTC, Mino777 commented
input을 main으로 이동시켜서 RacingGame()에 대한 테스트 커버리지를 100프로로 올려보았습니다!
감사합니다!

2021-11-14 14:05 UTC, zdodev approved these changes
@Mino777 안녕하세요!

스텝4 구현하시느라 고생하셨습니다.
테스트 커버리지가 높아지도록 수정한 점이 보입니다!

여기서 마무리하고 다음 스텝 진행해주시면 됩니다!😁

2021-11-14 14:05 UTC, zdodev commented on RacingCar/Step34/RacingGame.swift
> +    }
출력 역할을 따로 만들어주셨네요.👍

2021-11-14 14:05 UTC, merged