Step4, 5 - 자동차 경주(우승자) + (리펙토링)
next-step/swift-racingcar pull request #67
Opened 2022-05-02 13:26 UTC by Dev-RubinJo

자동차 경주(우승자)를 수행했습니다. 
그와 더불어 함께 step5도 같이 수행했습니다. 확인 부탁바랍니다.

2022-05-03 01:00 UTC, wonhee009 requested changes
수고하셨습니다 🎉 
코멘트 남겨두었으니 확인 부탁드려요 🙏

2022-05-03 01:00 UTC, wonhee009 commented on RacingCar/Car.swift
> +        if try Validator.checkValidation(number: randomNumber) >= canMoveMinNumber {
`Validator.checkValidation(number: _)`가 숫자를 반환하고 있는데요.
check 혹은 validation이라는 이름이라면 반환 타입이 Boolean여야 하지 않을까 생각이 듭니다.

```swift
Validator.checkValidation(number: _) -> Bool

guard Validator.checkValidation(number: randomNumber),
           randomNumber >= canMoveMinNumber else { return }
```
이런 방식은 어떤가요

2022-05-03 01:00 UTC, wonhee009 commented on RacingCar/Int+Extension.swift
> +    }
해당 메서드가 Int의 extension으로 정의되어야 하는 이유가 있을까요?
`Car`의 프로퍼티 중 가장 큰 moveCount를 판단하는 로직인데 모든 Int가 사용할 수 있어야 하나요?

2022-05-03 01:00 UTC, wonhee009 commented on RacingCar/Racing.swift
> +            try car.move(randomNumber: car.generateRandomNumber())
`car.move`를 하는데 `car.generateRandomNumber()`를 호출해서 주입해주는 부분이 어색한거 같습니다.
사실상 동일 한 car에 정의된 메서드인데요.
```swift
car { 
   func move()
   private func generateRandomNumber()
}
```
이렇게 `generateRandomNumber`을 private으로 감추고 move 로직 내에서 generateRandomNumber를 호출해도 좋을것 같구요.

랜덤한 숫자를 주입받고 싶다면 generateRandomNumber를 car가 아닌 외부로 분리해서 사용해도 좋을거 같습니다.

2022-05-03 01:00 UTC, wonhee009 commented on RacingCar/RacingCarOutput.swift
> +        }
이런 부분들도 car 내부에 정의하는건 어떨까요?
```swift
Car {
   var moveText: String {
      ...
   }
}
```

2022-05-03 09:43 UTC, Dev-RubinJo commented on RacingCar/Car.swift
> +        if try Validator.checkValidation(number: randomNumber) >= canMoveMinNumber {
와 제가 너무 값 체크하는 것을 이상하게 생각했네요. Validation 체크는 확실히 bool로 판단하는게 제일 명확한 것 같습니다. 적용하겠습니다.

2022-05-03 09:43 UTC, Dev-RubinJo commented on RacingCar/Int+Extension.swift
> +    }
제가 너무 Car에서 분리해야한다는 생각만 하다가 Int extension으로 빼뒀던 것 같습니다. 다만 아직 Int의 extension으로 처리해야겠다는 생각이 있어 RacingController에서만 처리할 수 있도록 하는 방법을 생각해보겠습니다.

2022-05-03 09:46 UTC, Dev-RubinJo commented on RacingCar/Racing.swift
> +            try car.move(randomNumber: car.generateRandomNumber())
처음에 작성할때는 그런 느낌을 받지 못했었는데 확실히 피드백해주시고 난 뒤 다시 보니까 car에서 랜덤 숫자 생성도 하고 그 숫자로 움직이는게 이상하긴 하군요. Generator를 만들어 처리하겠습니다!

2022-05-03 09:47 UTC, Dev-RubinJo commented on RacingCar/RacingCarOutput.swift
> +        }
해당부분은 ResultView에 가깝다고 생각하여 Car에 있는 것은 부적절하다고 생각합니다.

2022-05-05 02:53 UTC, wonhee009 approved these changes
수고하셨습니다 🎉

2022-05-05 02:53 UTC, merged